import app from './app'
import config from './config'
import { dataStore } from './data/store'

async function startServer() {
  await dataStore.init()

  app.listen(config.port, () => {
    console.log(`服务启动成功，运行在 http://localhost:${config.port}`)
    console.log(`健康检查: http://localhost:${config.port}/health`)
    console.log()
    console.log('=== API 接口列表 ===')
    console.log('用户相关:')
    console.log('  POST /api/users/register - 用户注册')
    console.log('  POST /api/users/login - 用户登录')
    console.log('  GET  /api/users/profile - 获取用户信息')
    console.log('  PUT  /api/users/profile - 更新用户信息')
    console.log()
    console.log('琴房相关:')
    console.log('  GET  /api/rooms - 获取琴房列表')
    console.log('  GET  /api/rooms/search/available - 搜索可用琴房')
    console.log('  GET  /api/rooms/:id - 获取琴房详情')
    console.log('  GET  /api/rooms/:id/availability - 获取琴房时段可用性')
    console.log('  POST /api/rooms - 创建琴房(管理员)')
    console.log('  PUT  /api/rooms/:id - 更新琴房(管理员)')
    console.log('  DELETE /api/rooms/:id - 删除琴房(管理员)')
    console.log()
    console.log('预约相关:')
    console.log('  GET  /api/bookings/availability - 查询时段可用性')
    console.log('  GET  /api/bookings/calculate-fee - 费用试算')
    console.log('  POST /api/bookings - 创建预约')
    console.log('  GET  /api/bookings/my - 获取我的预约')
    console.log('  GET  /api/bookings/:id - 获取预约详情')
    console.log('  POST /api/bookings/:id/cancel - 取消预约')
    console.log('  POST /api/bookings/:id/extend - 续时')
    console.log()
    console.log('核销相关:')
    console.log('  POST /api/verification/check-in - 到店核销')
    console.log('  POST /api/verification/check-out - 退房')
    console.log('  GET  /api/verification/overtime - 获取超时预约(管理员)')
    console.log('  GET  /api/verification/upcoming-reminders - 获取即将开始的预约提醒')
    console.log()
    console.log('临时闭店:')
    console.log('  GET  /api/closures - 获取闭店记录')
    console.log('  POST /api/closures - 创建闭店(管理员)')
    console.log('  PUT  /api/closures/:id/cancel - 取消闭店(管理员)')
    console.log()
    console.log('=== 测试账号 ===')
    console.log('管理员: 13800138000 / admin123')
    console.log('普通用户: 13900139000 / user123')
  })
}

startServer()
